// Code generated by model_gen
// article_test.go contains model test for the database table [blog.article]

package examples

import (
	"github.com/zhengyun1112/glorm/orm"
	"testing"
	"time"
)

func TestInsertAndGetArticle(t *testing.T) {
	orm.InitDefault("root:@/blog?parseTime=true&loc=Local")
	orm.TruncateTable("article")

	var article = &Article{
		UserId:    0,
		Title:     "",
		State:     0,
		Content:   "",
		Donation:  0,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	err := ArticleDao.Insert(article)
	if err != nil {
		t.Fatalf("failed to InsertArticle, err: %+v", err)
	}
	loaded, err := ArticleDao.GetByPK(article.ArticleId)
	if err != nil {
		t.Fatalf("failed to GetByPK, err: %+v", err)
	}
	if loaded == nil {
		t.Fatalf("should have loaded one Article")
	}
}
